# Generated by Django 5.0.1 on 2024-05-02 12:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_course_remove_instructor_messages_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='instructor',
        ),
        migrations.AddField(
            model_name='instructor',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.course'),
        ),
    ]
