# Generated by Django 5.0.1 on 2024-05-06 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_instructor_school_student_school'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='admin',
            field=models.CharField(default=False, max_length=100),
        ),
    ]
