# Generated by Django 5.0.1 on 2024-05-07 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='instructor',
        ),
        migrations.RemoveField(
            model_name='message',
            name='student',
        ),
    ]
