# Generated by Django 5.0.1 on 2024-05-07 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_remove_message_instructor_remove_message_student'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
