# Generated by Django 5.0.1 on 2024-05-09 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_message'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
