# Generated by Django 5.0.1 on 2024-05-09 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='cohort',
        ),
        migrations.RemoveField(
            model_name='student',
            name='cohort',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='course',
        ),
        migrations.RemoveField(
            model_name='instructor',
            name='course',
        ),
        migrations.RemoveField(
            model_name='message',
            name='course',
        ),
        migrations.RemoveField(
            model_name='student',
            name='course',
        ),
        migrations.DeleteModel(
            name='Cohort',
        ),
        migrations.DeleteModel(
            name='Topic',
        ),
        migrations.DeleteModel(
            name='Instructor',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
        migrations.DeleteModel(
            name='Course',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
