# Generated by Django 5.0.1 on 2024-05-09 20:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='exercise',
        ),
        migrations.AddField(
            model_name='exercise',
            name='topic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.topic'),
        ),
    ]
