# Generated by Django 5.0.6 on 2024-05-31 10:28

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_alter_topic_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='content',
            field=ckeditor.fields.RichTextField(default='nothing yet'),
            preserve_default=False,
        ),
    ]
