# Generated by Django 5.0.6 on 2024-07-13 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0019_topic_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='message',
            field=models.CharField(default='null', max_length=255),
        ),
    ]
