# Generated by Django 5.0.6 on 2024-07-13 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0020_exercise_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='message',
        ),
        migrations.AddField(
            model_name='studentexercisesubmission',
            name='message',
            field=models.CharField(default='null', max_length=255),
        ),
    ]
