# Generated by Django 5.0.6 on 2024-07-15 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0022_remove_studentexercisesubmission_message_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentexercisesubmission',
            name='message',
            field=models.CharField(default='null', max_length=255),
        ),
    ]
