# Generated by Django 5.0.6 on 2024-07-17 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0023_studentexercisesubmission_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='content',
            field=models.FileField(upload_to='notes/'),
        ),
    ]
