# Generated by Django 5.0.6 on 2024-07-18 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0026_school_instructor_student_studentexercisesubmission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructor',
            name='password',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='student',
            name='password',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
