# Generated by Django 5.0.6 on 2024-07-23 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0027_alter_instructor_password_alter_student_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
