# Generated by Django 5.0.6 on 2024-07-23 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0028_instructor_last_login'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instructor',
            name='last_login',
        ),
        migrations.AddField(
            model_name='instructor',
            name='reset_pin',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='reset_pin',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
