# Generated by Django 5.0.6 on 2024-07-25 06:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0030_post_media_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='media',
            name='media_type',
        ),
        migrations.AddField(
            model_name='media',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
